
const { getColors } = require("./colors");

function getTheme({ theme, name }) {
    const color = getColors(theme);
    return {
        name: name,
        colors: {
            foreground: "#ffffff",
            focusBorder: color.hidden,

            // descriptionForeground: color.fg.muted,
            // errorForeground: color.state.error,

            "selection.background": "#ffffff30",

            "textLink.foreground": "#277dff",
            "textLink.activeForeground": "#277dff",

            "widget.shadow": "#0000005c",
            "scrollbar.shadow": "#000000",

            // "textBlockQuote.background": color.canvas.inset,
            // "textBlockQuote.border"    : color.border.default,
            // "textCodeBlock.background" : color.neutral.muted,
            // "textPreformat.foreground" : color.fg.muted,
            // "textSeparator.foreground" : color.border.muted,

            "icon.foreground": "#ffffff",

            "button.background": "#222222",
            "button.foreground": "#ffffff",
            "button.hoverBackground": "#444444",
            "button.secondaryForeground": "#ffffff",
            "button.secondaryBackground": "#222222",
            "button.secondaryHoverBackground": "#444444",

            "checkbox.background": "#222222",
            "checkbox.foreground": "#ffffff",
            "checkbox.border": "#00000000",

            "dropdown.background": "#222222",
            "dropdown.foreground": "#ffffff",
            "dropdown.border": "#00000000",
            "dropdown.listBackground": "#222222",

            "input.background": "#222222",
            "input.border": "#00000000",
            "input.foreground": "#ffffff",
            "inputOption.activeBackground": "#ffffff33",
            "inputOption.activeBorder": "#ffffff00",
            "inputOption.activeForeground": "#ffffff",
            "input.placeholderForeground": "#cccccc",

            "badge.background": "#277dff",
            "badge.foreground": "#ffffff",

            "progressBar.background": "#277dff",

            "titleBar.activeBackground": "#000000",
            "titleBar.activeForeground": "#ffffff",
            "titleBar.inactiveBackground": "#000000",
            "titleBar.inactiveForeground": "#cccccc",
            "titleBar.border": "#00000000",

            "activityBar.foreground": "#ffffff",
            "activityBar.background": "#000000",
            "activityBar.inactiveForeground": "#ffffff66",
            "activityBarBadge.foreground": "#ffffff",
            "activityBarBadge.background": "#277dff",
            "activityBar.border": "#00000000",
            "activityBar.activeBackground": "#00000000",

            "sideBar.background": "#000000",
            "sideBar.foreground": "#ffffff",
            "sideBar.border": "#222222",
            "sideBar.dropBackground": "#222222",
            "sideBarSectionHeader.background": "#00000000",
            "sideBarSectionHeader.foreground": "#ffffff",
            "sideBarSectionHeader.border": "#cccccc00",
            "sideBarTitle.foreground": "#ffffff",

            "list.inactiveSelectionBackground": "#222222",
            "list.inactiveSelectionForeground": "#ffffff",
            "list.hoverBackground": "#222222",
            "list.hoverForeground": "#ffffff",
            "list.activeSelectionBackground": "#444444",
            "list.activeSelectionForeground": "#ffffff",
            "tree.indentGuidesStroke": "#444444",
            "list.dropBackground": "#222222",
            "list.highlightForeground": "#277dff",
            "list.focusBackground": "#444444",
            "list.focusForeground": "#ffffff",
            "listFilterWidget.background": "#444444",
            "listFilterWidget.outline": "#00000000",
            "listFilterWidget.noMatchesOutline": "#f2283c90",

            "notifications.foreground": "#ffffff",
            "notifications.background": "#111111",
            "notificationToast.border": "#111111",
            "notificationsErrorIcon.foreground": "#f2283c",
            "notificationsWarningIcon.foreground": "#ffc200",
            "notificationsInfoIcon.foreground": "#277dff",
            "notificationCenter.border": "#222222",
            "notificationCenterHeader.foreground": "#ffffff",
            "notificationCenterHeader.background": "#111111",
            "notifications.border": "#222222",

            "pickerGroup.border": "#444444",
            "pickerGroup.foreground": "#277dff",
            "quickInput.background": "#111111",
            "quickInput.foreground": "#ffffff",

            "statusBar.foreground": "#ffffff",
            "statusBar.background": "#000000",
            "statusBar.border": "#00000000",
            "statusBar.focusBorder": "#00000000",
            "statusBar.debuggingBackground": "#277dff",
            "statusBar.debuggingForeground": "#ffffff",
            "statusBar.debuggingBorder": "#00000000",
            "statusBar.noFolderBackground": "#ffc200",
            "statusBar.noFolderForeground": "#000000",
            "statusBar.noFolderBorder": "#00000000",

            "statusBarItem.focusBorder": "#00000000",
            "statusBarItem.hoverBackground": "#ffffff1f",
            "statusBarItem.remoteBackground": "#00ae6b",
            "statusBarItem.remoteForeground": "#ffffff",
            "statusBarItem.activeBackground": "#FFFFFF25",
            "statusBarItem.prominentBackground": "#FFFFFF80",

            "editorGroup.border": "#222222",
            "editorGroup.emptyBackground": "#000000",
            "editorGroupHeader.border": "#00000000",
            "editorGroupHeader.tabsBackground": "#000000",
            "editorGroupHeader.tabsBorder": "#00000000",

            "tab.activeForeground": "#ffffff",
            "tab.border": "#00000000",
            "tab.activeBackground": "#000000",
            "tab.activeBorder": "#00000000",
            "tab.activeBorderTop": "#ffffffcc",
            "tab.inactiveBackground": "#000000",
            "tab.inactiveForeground": "#ffffff80",
            "tab.hoverBackground": "#000000",
            "tab.hoverForeground": "#ffffffcc",
            "tab.hoverBorder": "#00000000",

            "breadcrumb.background": "#000000",
            "breadcrumb.foreground": "#cccccc",
            "breadcrumb.focusForeground": "#ffffff",
            "breadcrumb.activeSelectionForeground": "#ffffff",
            "breadcrumbPicker.background": "#000000",

            "editorWidget.foreground": "#ffffff",
            "editorWidget.background": "#222222",
            "editorWidget.resizeBorder": "#444444",

            "editor.background": "#000000",
            "editor.foreground": "#ffffff",
            "editor.foldBackground": "#22222280",
            "editor.hoverHighlightBackground": "#264f7840",
            "editorLink.activeForeground": "#277dff",
            "editor.lineHighlightBackground": "#00000000",
            "editor.lineHighlightBorder": "#00000000",
            "editorLineNumber.activeForeground": "#ffffff",
            "editorLineNumber.foreground": "#666666",
            "editorIndentGuide.activeBackground": "#ffffff50",
            "editorIndentGuide.background": "#ffffff30",
            "editorWhitespace.foreground": "#ffffff20",

            "editorCursor.background": "#000000",
            "editorCursor.foreground": "#ffffff",

            "editor.findMatchBackground": "#277dff90",
            "editor.findMatchBorder": "#00000000",
            "editor.findMatchHighlightBackground": "#277dff50",
            "editor.findMatchHighlightBorder": "#00000000",
            "editor.findRangeHighlightBackground": "#ffffff20",
            "editor.findRangeHighlightBorder": "#00000000",
            "editor.rangeHighlightBackground": "#277dff50",
            "editor.rangeHighlightBorder": "#00000000",
            "editor.inactiveSelectionBackground": "#33333380",
            "editor.selectionBackground": "#444444",
            "editor.selectionHighlightBackground": "#ffffff25",
            "editor.selectionHighlightBorder": "#00000000",
            "editor.wordHighlightBackground": "#00000000",
            "editor.wordHighlightBorder": "#00000000",
            "editor.wordHighlightStrongBackground": "#00000000",
            "editor.wordHighlightStrongBorder": "#00000000",
            "editorBracketMatch.background": "#00000000",
            "editorBracketMatch.border": "#00000000",
            "editorCodeLens.foreground": "#aaaaaa",

            "editorHoverWidget.foreground": "#ffffff",
            "editorHoverWidget.background": "#111111",
            "editorHoverWidget.border": "#111111",

            // "editorInlayHint.background": alpha(scale.gray[3], 0.2),
            // "editorInlayHint.foreground": color.fg.muted,
            // "editorInlayHint.typeBackground": alpha(scale.gray[3], 0.2),
            // "editorInlayHint.typeForeground": color.fg.muted,
            // "editorInlayHint.paramBackground": alpha(scale.gray[3], 0.2),
            // "editorInlayHint.paramForeground": color.fg.muted,

            "editorError.background": "#00000000",
            "editorError.border": "#00000000",
            "editorError.foreground": "#f2283c",
            "editorInfo.background": "#00000000",
            "editorInfo.border": "#00000000",
            "editorInfo.foreground": "#277dff",
            "editorWarning.background": "#00000000",
            "editorWarning.border": "#00000000",
            "editorWarning.foreground": "#ffc200",

            "editorGutter.addedBackground": "#00ae6b",
            "editorGutter.background": "#00000000",
            "editorGutter.commentRangeForeground": "#888888",
            "editorGutter.deletedBackground": "#f2283c",
            "editorGutter.foldingControlForeground": "#888888",
            "editorGutter.modifiedBackground": "#277dff",

            "editorSuggestWidget.background": "#111111",
            "editorSuggestWidget.border": "#111111",
            "editorSuggestWidget.foreground": "#ffffff",
            "editorSuggestWidget.highlightForeground": "#ffffff",
            "editorSuggestWidget.selectedBackground": "#222222",

            "editorMarkerNavigation.background": "#000000",
            "editorMarkerNavigationError.background": "#f2283c",
            "editorMarkerNavigationWarning.background": "#ffc200",
            "editorMarkerNavigationInfo.background": "#277dff",

            // "diffEditor.insertedLineBackground": lightDark(alpha(scale.green[1], 0.3), alpha(scale.green[5], 0.15)),
            // "diffEditor.removedLineBackground" : lightDark(alpha(scale.red[1], 0.3), alpha(scale.red[5], 0.15)),
            "diffEditor.insertedTextBackground": "#00ae6b33",
            "diffEditor.removedTextBackground": "#f2283c33",
            "diffEditor.border": "#222222",

            "scrollbar.shadow": "#00000000",
            "scrollbarSlider.background": "#00000040",
            "scrollbarSlider.hoverBackground": "#ffffff20",
            "scrollbarSlider.activeBackground": "#aaaaaa20",
            "editorOverviewRuler.background": "#000000",
            "editorOverviewRuler.border": "#000000",
            "editorRuler.foreground": "#444444",

            "minimapGutter.addedBackground": "#00ae6b",
            "minimapGutter.modifiedBackground": "#277dff",
            "minimapGutter.deletedBackground": "#f2283c",
            "minimap.findMatchHighlight": "#277dff90",
            "minimap.selectionHighlight": "#44444480",
            "minimap.errorHighlight": "#f2283c",
            "minimap.warningHighlight": "#ffc200",
            "minimap.background": "#000000",

            "panel.background": "#000000",
            "panel.border": "#ffffff00",
            "panelSection.border": "#ffffff40",
            "panelTitle.activeBorder": "#ffffff",
            "panelTitle.activeForeground": "#ffffff",
            "panelTitle.inactiveForeground": "#ffffff66",
            "panelInput.border": "#00000000",

            // "debugIcon.breakpointForeground": color.danger.fg,

            // "debugConsole.infoForeground": lightDark( scale.gray[6], scale.gray[3]),
            // "debugConsole.warningForeground": lightDark( scale.yellow[6], scale.yellow[3]),
            // "debugConsole.errorForeground": lightDark( scale.red[5], scale.red[2]),
            // "debugConsole.sourceForeground": lightDark( scale.yellow[5], scale.yellow[2]),
            // "debugConsoleInputIcon.foreground": lightDark( scale.purple[6], scale.purple[3]),

            // "debugTokenExpression.name": lightDark(scale.blue[6], scale.blue[2]),
            // "debugTokenExpression.value": lightDark(scale.blue[8], scale.blue[1]),
            // "debugTokenExpression.string": lightDark(scale.blue[8], scale.blue[1]),
            // "debugTokenExpression.boolean": lightDark( scale.green[6], scale.green[2]),
            // "debugTokenExpression.number": lightDark( scale.green[6], scale.green[2]),
            // "debugTokenExpression.error": lightDark( scale.red[6], scale.red[2]),

            "debugExceptionWidget.background": "#222222",
            "debugExceptionWidget.border": "#222222",

            // "symbolIcon.arrayForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.booleanForeground": lightDark( scale.blue[6], scale.blue[3]),
            // "symbolIcon.classForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.colorForeground": lightDark( scale.blue[8], scale.blue[2]),
            // "symbolIcon.constructorForeground": lightDark( scale.purple[8], scale.purple[2]),
            // "symbolIcon.enumeratorForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.enumeratorMemberForeground": lightDark( scale.blue[6], scale.blue[3]),
            // "symbolIcon.eventForeground": lightDark( scale.gray[6], scale.gray[4]),
            // "symbolIcon.fieldForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.fileForeground": lightDark( scale.yellow[6], scale.yellow[3]),
            // "symbolIcon.folderForeground": lightDark( scale.yellow[6], scale.yellow[3]),
            // "symbolIcon.functionForeground": lightDark( scale.purple[6], scale.purple[3]),
            // "symbolIcon.interfaceForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.keyForeground": lightDark( scale.blue[6], scale.blue[3]),
            // "symbolIcon.keywordForeground": lightDark( scale.red[6], scale.red[3]),
            // "symbolIcon.methodForeground": lightDark( scale.purple[6], scale.purple[3]),
            // "symbolIcon.moduleForeground": lightDark( scale.red[6], scale.red[3]),
            // "symbolIcon.namespaceForeground": lightDark( scale.red[6], scale.red[3]),
            // "symbolIcon.nullForeground": lightDark( scale.blue[6], scale.blue[3]),
            // "symbolIcon.numberForeground": lightDark( scale.green[6], scale.green[3]),
            // "symbolIcon.objectForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.operatorForeground": lightDark( scale.blue[8], scale.blue[2]),
            // "symbolIcon.packageForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.propertyForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.referenceForeground": lightDark( scale.blue[6], scale.blue[3]),
            // "symbolIcon.snippetForeground": lightDark( scale.blue[6], scale.blue[3]),
            // "symbolIcon.stringForeground": lightDark( scale.blue[8], scale.blue[2]),
            // "symbolIcon.structForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.textForeground": lightDark( scale.blue[8], scale.blue[2]),
            // "symbolIcon.typeParameterForeground": lightDark( scale.blue[8], scale.blue[2]),
            // "symbolIcon.unitForeground": lightDark( scale.blue[6], scale.blue[3]),
            // "symbolIcon.variableForeground": lightDark( scale.orange[6], scale.orange[3]),
            // "symbolIcon.constantForeground": lightDark( scale.green[6], scale.green),

            "terminal.foreground": "#ffffff",
            "terminal.selectionBackground": "#ffffff30",
            "terminalCursor.background": "#ffffff",
            "terminalCursor.foreground": "#000000",
            "terminal.border": "#ffffff40",
            "terminal.ansiBlack": "#000000",
            "terminal.ansiBlue": "#277dff",
            "terminal.ansiBrightBlack": "#666666",
            "terminal.ansiBrightBlue": "#277dff",
            "terminal.ansiBrightCyan": "#875afb",
            "terminal.ansiBrightGreen": "#00ae6b",
            "terminal.ansiBrightMagenta": "#d72e82",
            "terminal.ansiBrightRed": "#f2283c",
            "terminal.ansiBrightWhite": "#ffffff",
            "terminal.ansiBrightYellow": "#ffc200",
            "terminal.ansiCyan": "#875afb",
            "terminal.ansiGreen": "#00ae6b",
            "terminal.ansiMagenta": "#d72e82",
            "terminal.ansiRed": "#f2283c",
            "terminal.ansiWhite": "#ffffff",
            "terminal.ansiYellow": "#ffc200",

            // "editorBracketHighlight.foreground1": lightDark(scale.blue[5], scale.blue[2]),
            // "editorBracketHighlight.foreground2": lightDark(scale.green[5], scale.green[2]),
            // "editorBracketHighlight.foreground3": lightDark(scale.yellow[5], scale.yellow[2]),
            // "editorBracketHighlight.foreground4": lightDark(scale.red[5], scale.red[2]),
            // "editorBracketHighlight.foreground5": lightDark(scale.pink[5], scale.pink[2]),
            // "editorBracketHighlight.foreground6": lightDark(scale.purple[5], scale.purple[2]),
            // "editorBracketHighlight.unexpectedBracket.foreground": color.fg.muted, // gray

            "gitDecoration.addedResourceForeground": "#00ae6b",
            "gitDecoration.conflictingResourceForeground": "#875afb",
            "gitDecoration.deletedResourceForeground": "#f2283c",
            "gitDecoration.ignoredResourceForeground": "#666666",
            "gitDecoration.modifiedResourceForeground": "#ffc200",
            "gitDecoration.stageDeletedResourceForeground": "#f2283c",
            "gitDecoration.stageModifiedResourceForeground": "#ffc200",
            "gitDecoration.submoduleResourceForeground": "#277dff",
            "gitDecoration.untrackedResourceForeground": "#00ae6b",

            "merge.currentHeaderBackground": "#875afbaa",
            "merge.currentContentBackground": "#875afbaa",
            "merge.incomingHeaderBackground": "#d72e82aa",
            "merge.incomingContentBackground": "#d72e82aa",
            "merge.commonHeaderBackground": "#222222aa",
            "merge.commonContentBackground": "#111111aa",

            "debugToolBar.background": "#222222",
            "debugToolBar.border": "#222222",
            // "editor.stackFrameHighlightBackground"       : color.attention.muted,
            // "editor.focusedStackFrameHighlightBackground": color.success.muted,

            "peekView.border": "#222222",
            "peekViewEditor.background": "#000000",
            "peekViewEditorGutter.background": "#000000",
            "peekViewEditor.matchHighlightBackground": "#277dff90",
            "peekViewEditor.matchHighlightBorder": "#00000000",
            "peekViewResult.background": "#000000",
            "peekViewResult.fileForeground": "#ffffff",
            "peekViewResult.lineForeground": "#ffffff",
            "peekViewResult.matchHighlightBackground": "#277dff90",
            "peekViewResult.selectionBackground": "#222222",
            "peekViewResult.selectionForeground": "#ffffff",
            "peekViewTitle.background": "#000000",
            "peekViewTitleDescription.foreground": "#ffffff",
            "peekViewTitleLabel.foreground": "#ffffff",

            "settings.headerForeground": "#ffffff",
            "settings.focusedRowBackground": "#ffffff07",
            "settings.modifiedItemIndicator": "#ffc200",
            "walkThrough.embeddedEditorBackground": "#00000050",

            // "welcomePage.buttonBackground"     : color.btn.bg,
            // "welcomePage.buttonHoverBackground": color.btn.hoverBg,
        },
        semanticHighlighting: true,
        semanticTokenColors: {
            enumMember: {
                foreground: "#ffffff",
            },
            "variable.constant": {
                foreground: "#ffffff",
            },
            "variable.defaultLibrary": {
                foreground: "#ffffff",
            },
        },
    };
}

module.exports = getTheme;
