const { alpha, getColors } = require("./colors");

function getTheme({ theme, name }) {
    const color = getColors(theme);
    return {
        name: name,
        colors: {
            focusBorder: color.hidden,
            foreground: color.interface.foreground,
            "widget.shadow": color.interface.shadow,
            "widget.border": color.interface.border,
            "selection.background": color.editor.selection,
            descriptionForeground: color.interface.foreground,
            errorForeground: color.state.error,
            "icon.foreground": color.interface.foreground,

            "textLink.foreground": color.interface.link,
            "textLink.activeForeground": color.interface.link,

            "button.background": color.interface.button,
            "button.foreground": color.interface.foreground,
            "button.border": color.hidden,
            "button.separator": color.interface.foreground,
            "button.hoverBackground": color.interface.hover,
            "button.secondaryForeground": color.interface.foreground,
            "button.secondaryBackground": color.interface.button,
            "button.secondaryHoverBackground": color.interface.hover,

            "checkbox.background": color.interface.input,
            "checkbox.foreground": color.interface.foreground,
            "checkbox.border": color.hidden,

            "dropdown.background": color.interface.button,
            "dropdown.foreground": color.interface.foreground,
            "dropdown.border": color.hidden,
            "dropdown.listBackground": color.interface.button,

            "input.background": color.interface.input,
            "input.border": color.hidden,
            "input.foreground": color.foreground.default,
            "input.placeholderForeground": color.interface.muted,
            "inputOption.activeBackground": color.editor.selection,
            "inputOption.activeBorder": color.hidden,
            "inputOption.activeForeground": color.foreground.default,

            "scrollbar.shadow": color.hidden,
            "scrollbarSlider.background": alpha("#ffffff", 0.15),
            "scrollbarSlider.hoverBackground": alpha("#ffffff", 0.4),
            "scrollbarSlider.activeBackground": alpha("#ffffff", 0.4),

            "badge.background": color.interface.background,
            "badge.foreground": color.foreground.default,

            "progressBar.background": color.interface.muted,

            "list.activeSelectionBackground": color.interface.button,
            "list.activeSelectionForeground": color.foreground.default,
            "list.inactiveSelectionBackground": color.interface.button,
            "list.inactiveSelectionForeground": color.foreground.default,
            "list.hoverBackground": color.interface.button,
            "list.hoverForeground": color.foreground.default,
            "tree.indentGuidesStroke": color.interface.border,
            "list.dropBackground": color.interface.hover,
            "list.highlightForeground": color.editor.match,
            "list.focusBackground": color.interface.button,
            "list.focusForeground": color.foreground.default,
            "listFilterWidget.background": color.button,
            "listFilterWidget.outline": color.hidden,
            "listFilterWidget.noMatchesOutline": color.state.error,

            "activityBar.foreground": color.foreground.default,
            "activityBar.background": color.background.default,
            "activityBar.inactiveForeground": color.foreground.comment,
            "activityBarBadge.foreground": color.foreground.default,
            "activityBarBadge.background": color.background.default,
            "activityBar.border": color.hidden,
            "activityBar.activeBackground": color.hidden,

            "sideBar.background": color.background.default,
            "sideBar.foreground": color.foreground.default,
            "sideBar.border": color.interface.border,
            "sideBar.dropBackground": color.interface.hover,
            "sideBarSectionHeader.background": color.hidden,
            "sideBarSectionHeader.foreground": color.foreground.default,
            "sideBarSectionHeader.border": color.hidden,
            "sideBarTitle.foreground": color.foreground.default,

            "minimapGutter.addedBackground": color.state.pass,
            "minimapGutter.modifiedBackground": color.state.info,
            "minimapGutter.deletedBackground": color.state.error,
            "minimap.findMatchHighlight": color.editor.match,
            "minimap.selectionHighlight": color.editor.selection,
            "minimap.errorHighlight": color.state.error,
            "minimap.warningHighlight": color.state.warning,
            "minimap.background": color.background.default,

            "editorGroup.border": color.interface.border,
            "editorGroup.emptyBackground": color.background.default,
            "editorGroupHeader.border": color.hidden,
            "editorGroupHeader.tabsBackground": color.background.default,
            "editorGroupHeader.tabsBorder": color.hidden,

            "tab.activeForeground": color.foreground.default,
            "tab.border": color.hidden,
            "tab.activeBackground": color.background.default,
            "tab.activeBorder": color.hidden,
            "tab.activeBorderTop": color.interface.muted,
            "tab.inactiveBackground": color.background.default,
            "tab.inactiveForeground": color.interface.muted,
            "tab.hoverBackground": color.background.default,
            "tab.hoverForeground": color.interface.muted,
            "tab.hoverBorder": color.hidden,

            "editor.background": color.background.default,
            "editor.foreground": color.foreground.default,
            "editorLineNumber.activeForeground": color.foreground.default,
            // TODO: Find a good name for this
            "editorLineNumber.foreground": "#666666",
            "editorCursor.background": color.background.default,
            "editorCursor.foreground": color.foreground.default,

            "editor.selectionBackground": color.editor.selection,
            "editor.selectionHighlightBackground": alpha(color.interface.foreground, 0.25),
            "editor.selectionHighlightBorder": color.hidden,
            "editor.wordHighlightBackground": color.hidden,
            "editor.wordHighlightBorder": color.hidden,
            "editor.wordHighlightStrongBackground": color.hidden,
            "editor.wordHighlightStrongBorder": color.hidden,

            "editor.findMatchForeground": color.foreground.default,
            "editor.findMatchBackground": alpha(color.editor.match, 0.8),
            "editor.findMatchHighlightForeground": color.interface.foreground,
            "editor.findMatchHighlightBackground": alpha(color.editor.match, 0.3),
            "editor.findMatchHighlightBorder": color.hidden,
            "editor.findMatchBorder": color.hidden,
            "editor.findRangeHighlightBackground": color.editor.range,
            "editor.findRangeHighlightBorder": color.hidden,
            "editor.hoverHighlightBackground": color.editor.selection,
            "editor.lineHighlightBackground": color.hidden,
            "editor.lineHighlightBorder": color.hidden,
            "editor.rangeHighlightBackground": color.hidden,
            "editor.rangeHighlightBorder": color.hidden,
            "editorLink.activeForeground": color.interface.link,
            "editorWhitespace.foreground": alpha(color.interface.foreground, 0.15),

            "editorIndentGuide.activeBackground": alpha(color.interface.foreground, 0.35),
            "editorIndentGuide.activeBackground1": alpha(color.interface.foreground, 0.35),
            "editorIndentGuide.activeBackground2": alpha(color.interface.foreground, 0.35),
            "editorIndentGuide.activeBackground3": alpha(color.interface.foreground, 0.35),
            "editorIndentGuide.activeBackground4": alpha(color.interface.foreground, 0.35),
            "editorIndentGuide.activeBackground5": alpha(color.interface.foreground, 0.35),
            "editorIndentGuide.activeBackground6": alpha(color.interface.foreground, 0.35),
            "editorIndentGuide.background1": alpha(color.interface.foreground, 0.2),
            "editorIndentGuide.background2": alpha(color.interface.foreground, 0.2),
            "editorIndentGuide.background3": alpha(color.interface.foreground, 0.2),
            "editorIndentGuide.background4": alpha(color.interface.foreground, 0.2),
            "editorIndentGuide.background5": alpha(color.interface.foreground, 0.2),
            "editorIndentGuide.background6": alpha(color.interface.foreground, 0.2),
            "editorIndentGuide.background": alpha(color.interface.foreground, 0.2),

            "editorRuler.foreground": color.interface.hover,
            "editorCodeLens.foreground": color.interface.muted,
            "editorBracketMatch.background": color.hidden,
            "editorBracketMatch.border": color.hidden,
            "editorBracketHighlight.foreground1": color.foreground.default,
            "editorBracketHighlight.foreground2": color.foreground.default,
            "editorBracketHighlight.foreground3": color.foreground.default,
            "editorBracketHighlight.foreground4": color.foreground.default,
            "editorBracketHighlight.foreground5": color.foreground.default,
            "editorBracketHighlight.foreground6": color.foreground.default,
            "editorBracketHighlight.unexpectedBracket.foreground": color.state.error,

            "editor.foldBackground": alpha(color.interface.hover, 0.75),

            "editorOverviewRuler.background": color.background.default,
            "editorOverviewRuler.border": color.background.default,

            "editorError.background": color.hidden,
            "editorError.border": color.hidden,
            "editorError.foreground": color.state.error,
            "editorInfo.background": color.hidden,
            "editorInfo.border": color.hidden,
            "editorInfo.foreground": color.state.info,
            "editorWarning.background": color.hidden,
            "editorWarning.border": color.hidden,
            "editorWarning.foreground": color.state.warning,

            "editorGutter.addedBackground": color.state.pass,
            "editorGutter.background": color.hidden,
            "editorGutter.commentRangeForeground": color.editor.comment,
            "editorGutter.deletedBackground": color.state.error,
            "editorGutter.foldingControlForeground": color.editor.comment,
            "editorGutter.modifiedBackground": color.state.info,

            "diffEditor.insertedTextBackground": alpha(color.state.pass, 0.33),
            "diffEditor.removedTextBackground": alpha(color.state.error, 0.33),
            "diffEditor.border": color.interface.border,

            // TODO: Finish second pass
            // TODO Decide if we want input or full dark BG

            "editorWidget.foreground": color.interface.foreground,
            "editorWidget.background": color.interface.background,
            "editorWidget.resizeBorder": color.interface.hover,

            "editorSuggestWidget.background": color.interface.background,
            "editorSuggestWidget.border": color.interface.input,
            "editorSuggestWidget.foreground": color.foreground.default,
            "editorSuggestWidget.highlightForeground": color.foreground.default,
            "editorSuggestWidget.selectedBackground": color.interface.hover,

            "editorHoverWidget.foreground": color.foreground.default,
            "editorHoverWidget.background": color.interface.background,
            "editorHoverWidget.border": color.interface.input,

            "debugExceptionWidget.background": color.interface.input,
            "debugExceptionWidget.border": color.interface.input,

            "editorMarkerNavigation.background": color.background.default,
            "editorMarkerNavigationError.background": color.state.error,
            "editorMarkerNavigationWarning.background": color.state.warning,
            "editorMarkerNavigationInfo.background": color.state.info,

            "peekView.border": color.interface.border,
            "peekViewEditor.background": color.background.default,
            "peekViewEditorGutter.background": color.background.default,
            "peekViewEditor.matchHighlightBackground": color.editor.match,
            "peekViewEditor.matchHighlightBorder": color.hidden,
            "peekViewResult.background": color.background.default,
            "peekViewResult.fileForeground": color.foreground.default,
            "peekViewResult.lineForeground": color.foreground.default,
            "peekViewResult.matchHighlightBackground": color.editor.match,
            "peekViewResult.selectionBackground": color.editor.selection,
            "peekViewResult.selectionForeground": color.foreground.default,
            "peekViewTitle.background": color.background.default,
            "peekViewTitleDescription.foreground": color.foreground.default,
            "peekViewTitleLabel.foreground": color.foreground.default,

            // TODO: Alphas
            "merge.currentHeaderBackground": "#875afbaa",
            "merge.currentContentBackground": "#875afbaa",
            "merge.incomingHeaderBackground": "#d72e82aa",
            "merge.incomingContentBackground": "#d72e82aa",
            "merge.commonHeaderBackground": "#222222aa",
            "merge.commonContentBackground": "#111111aa",

            "panel.background": color.background.default,
            "panel.border": color.interface.border,
            "panelSection.border": color.interface.border,
            "panelTitle.activeBorder": color.foreground.default,
            "panelTitle.activeForeground": color.foreground.default,
            "panelTitle.inactiveForeground": color.foreground.comment,
            "panelInput.border": color.hidden,

            "statusBar.foreground": color.foreground.default,
            "statusBar.background": color.background.default,
            "statusBar.border": color.hidden,
            "statusBar.focusBorder": color.hidden,
            "statusBar.debuggingBackground": color.background.default,
            "statusBar.debuggingForeground": color.foreground.default,
            "statusBar.debuggingBorder": color.hidden,
            "statusBar.noFolderBackground": color.background.default,
            "statusBar.noFolderForeground": color.background.default,
            "statusBar.noFolderBorder": color.hidden,
            "statusBarItem.focusBorder": color.hidden,
            "statusBarItem.hoverBackground": color.foreground.default,
            "statusBarItem.remoteBackground": color.editor.selection,
            "statusBarItem.remoteForeground": color.foreground.default,
            "statusBarItem.activeBackground": color.background.default,
            "statusBarItem.prominentBackground": color.state.warning,

            "titleBar.activeBackground": color.background.default,
            "titleBar.activeForeground": color.foreground.default,
            "titleBar.inactiveBackground": color.background.default,
            "titleBar.inactiveForeground": color.foreground.comment,
            "titleBar.border": color.hidden,

            "notifications.foreground": color.foreground.default,
            "notifications.background": color.interface.input,
            "notificationToast.border": color.interface.input,
            "notificationsErrorIcon.foreground": color.state.error,
            "notificationsWarningIcon.foreground": color.state.warning,
            "notificationsInfoIcon.foreground": color.state.info,
            "notificationCenter.border": color.interface.border,
            "notificationCenterHeader.foreground": color.foreground.default,
            "notificationCenterHeader.background": color.interface.input,
            "notifications.border": color.interface.border,

            "pickerGroup.border": color.interface.border,
            "pickerGroup.foreground": color.foreground.accent,
            "quickInput.background": color.interface.input,
            "quickInput.foreground": color.foreground.default,

            "terminal.foreground": color.foreground.default,
            "terminal.background": color.background.default,
            "terminal.selectionBackground": color.editor.selection,
            "terminal.border": "#ffffff40",
            "terminal.ansiBlack": color.background.default,
            "terminal.ansiBlue": "#277dff",
            "terminal.ansiBrightBlack": "#666666",
            "terminal.ansiBrightBlue": "#277dff",
            "terminal.ansiBrightCyan": "#875afb",
            "terminal.ansiBrightGreen": "#00ae6b",
            "terminal.ansiBrightMagenta": "#d72e82",
            "terminal.ansiBrightRed": color.state.error,
            "terminal.ansiBrightWhite": color.foreground.default,
            "terminal.ansiBrightYellow": "#ffc200",
            "terminal.ansiCyan": "#875afb",
            "terminal.ansiGreen": "#00ae6b",
            "terminal.ansiMagenta": "#d72e82",
            "terminal.ansiRed": color.state.error,
            "terminal.ansiWhite": color.foreground.default,
            "terminal.ansiYellow": "#ffc200",

            "debugToolBar.background": color.interface.input,
            "debugToolBar.border": color.interface.border,

            "gitDecoration.addedResourceForeground": color.state.pass,
            "gitDecoration.conflictingResourceForeground": "#875afb",
            "gitDecoration.deletedResourceForeground": color.state.error,
            "gitDecoration.ignoredResourceForeground": color.foreground.comment,
            "gitDecoration.modifiedResourceForeground": "#ffc200",
            "gitDecoration.stageDeletedResourceForeground": color.state.error,
            "gitDecoration.stageModifiedResourceForeground": "#ffc200",
            "gitDecoration.submoduleResourceForeground": "#277dff",
            "gitDecoration.untrackedResourceForeground": color.state.pass,

            "breadcrumb.background": color.background.default,
            "breadcrumb.foreground": color.foreground.comment,
            "breadcrumb.focusForeground": color.foreground.default,
            "breadcrumb.activeSelectionForeground": color.foreground.default,
            "breadcrumbPicker.background": color.background.default,
        },
        semanticHighlighting: true,
        semanticTokenColors: {
            enumMember: {
                foreground: color.foreground.default,
            },
            "variable.constant": {
                foreground: color.foreground.default,
            },
            "variable.defaultLibrary": {
                foreground: color.foreground.default,
            },
        },
    };
}

module.exports = getTheme;
